name: CI

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js 22.20.0
        uses: actions/setup-node@v4
        with:
          node-version: 22.20.0
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Prettier check
        run: npm run prettier:check

  build:
    runs-on: ubuntu-latest
    needs: prettier
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js 22.20.0
        uses: actions/setup-node@v4
        with:
          node-version: 22.20.0
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build
