name: "Check PR title format"

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
uses: amannn/action-semantic-pull-request@v5
      with:
        subjectPattern: "^PWA-[0-9]+: .+"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
